M48
; DRILL file {KiCad (6.0.5)} date Mon Jun 13 10:30:55 2022
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2022-06-13T10:30:55+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X53300Y-38000
X53300Y-39000
X55300Y-38000
X55300Y-39000
T0
M30
